# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='categories',
            field=models.ManyToManyField(blank=True, to='categories.Category'),
        ),
    ]
