# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeedevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedevice',
            name='android_device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeedevice',
            name='ios_device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
