# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='to_user',
            field=models.CharField(max_length=250),
        ),
    ]
