# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 14:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20160712_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.CharField(default=datetime.datetime(2016, 7, 13, 14, 26, 55, 183464, tzinfo=utc), max_length=140),
            preserve_default=False,
        ),
    ]
