# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20160713_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='from_user',
        ),
        migrations.AlterField(
            model_name='activity',
            name='detail',
            field=models.CharField(max_length=140),
        ),
    ]
