# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-18 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20160713_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='detail',
            new_name='text',
        ),
    ]
