# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ManyToManyField(to='categories.Category')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'subcategories',
            },
        ),
    ]
