# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-27 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='comment_required',
            field=models.BooleanField(default=True),
        ),
    ]
