# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 14:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(blank=True, max_length=140, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_from', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Subcategory')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'to_user'],
            },
        ),
    ]
