# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-27 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='sharing_text',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
